//"use client"
import Link from "next/link";
import "./globals.css";
//import { useEffect, useState } from "react";

// export const metadata = {
//   title: "Web tutorial",
//   description: "Generated by zend",
// };

export default async function RootLayout({ children }) {
  // const [topics, setTopics] = useState([]);
  // useEffect(()=>{
  //   fetch('http://localhost:9999/topics')
  //     .then(resp=>resp.json())
  //     .then(result=>{
  //       setTopics(result)
  //     });
  // },[]);
  const resp = await fetch('http://localhost:9999/topics');
  const topics = await resp.json();

  return (
    <html>
      <body>
        <h1><a href="/">WEB</a></h1>
        <ol>
          {topics.map((topic)=>{
            return <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>
          })}
        </ol>
        {children}
        <ul>
          <li><Link href="/create">Create</Link></li>
          <li><Link href="/update">Update</Link></li>
          <li><input type="button" value="delete" /></li>
        </ul>
      </body>
    </html>
  );
}
